<?php
/**
 * @file
 * whami Source Adapter module
 */

/**
 * Function that request for data to a source adapter
 * from certain Bounding Box
 *
 * @param array $bbox
 *   bounding box
 * @param string $lan
 *   language
 * @param array $categories_id
 *   categories
 * @param string $source_id
 *   source id
 * @param int $max_rows
 *   maximum rows to return
 * @param int $titleshrink
 *   titleshrink
 * @param int $bodyshrink
 *   titleshrink
 * @param int $linkshrink
 *   titleshrink
 * @param int $max_request_rows
 *   maximum rows to request
 * @param string $session_id
 *   session id
 *
 * @return Parsed response from the specific source adapter
 */
function whami_source_adapter_bounding_box($bbox, $lan, $categories_id, $source_id, $max_rows, $titleshrink, $bodyshrink, $linkshrink, $max_request_rows, $session_id) {
  if (module_exists('whami_source_adapter_' . $source_id) && function_exists('whami_source_adapter_' . $source_id . '_bounding_box')) {
    $function = 'whami_source_adapter_' . $source_id . '_bounding_box';
    $result = $function($bbox, $lan, $max_request_rows);
    return whami_source_adapter_parse_response($result, $max_rows, $titleshrink, $bodyshrink, $linkshrink, $categories_id, $source_id, $session_id);
  }
  else {
    drupal_set_message(t("The required Whami data source is not available. Please install the whami_source_adapter_@name module", array("@name" => $source_id)), 'error');
  }
}

/**
 * Function that request for data to a source adapter
 * from certain Geopoint and Radius
 *
 * @param double $lat
 *   latitude
 * @param double $lon
 *   longitude
 * @param int $radius
 *   radius
 * @param string $lan
 *   language
 * @param array $categories_id
 *   categories
 * @param string $source_id
 *   source id
 * @param int $max_rows
 *   maximum rows to return
 * @param int $titleshrink
 *   titleshrink
 * @param int $bodyshrink
 *   titleshrink
 * @param int $linkshrink
 *   titleshrink
 * @param int $max_request_rows
 *   maximum rows to request
 * @param string $session_id
 *   session id
 *
 * @return Parsed response from the specific source adapter
 */
function whami_source_adapter_geopoint_radius($lat, $lon, $radius, $lan, $categories_id, $source_id, $max_rows, $titleshrink, $bodyshrink, $linkshrink, $max_request_rows, $session_id) {
  if (module_exists('whami_source_adapter_' . $source_id) && function_exists('whami_source_adapter_' . $source_id . '_geopoint_radius')) {
    $function = 'whami_source_adapter_' . $source_id . '_geopoint_radius';
    $result = $function($lat, $lon, $radius, $lan, $max_request_rows);
    return whami_source_adapter_parse_response($result, $max_rows, $titleshrink, $bodyshrink, $linkshrink, $categories_id, $source_id, $session_id);
  }
  else {
    drupal_set_message(t("The required Whami data source is not available. Please install the whami_source_adapter_@name module", array("@name" => $source_id)), 'error');
  }
}

/**
 *  Function that parses the results from an specific source adapter
 *  to the main format
 *
 * @param array $result
 *   result
 * @param int $max_rows
 *   maximum rows
 * @param int $titleshrink
 *   titleshrink
 * @param int $bodyshrink
 *   bodyshrink
 * @param int $linkshrink
 *   linkshrink
 * @param string $session_id
 *   sesion id
 *
 * @return Parsed response for the Source Adapter
 */
function whami_source_adapter_parse_response($result, $max_rows, $titleshrink, $bodyshrink, $linkshrink, $categories_id, $source_id, $session_id) {
  $result = array_slice($result, 0, $max_rows);

  foreach ($result as $key => $value) {
    $result[$key]['sourceID'] = $source_id;
    $result[$key]['categoryID'] = $categories_id;

    $result[$key]['title'] = substr($result[$key]['title'], 0, $titleshrink);
    $result[$key]['body'] = substr($result[$key]['body'], 0, $bodyshrink);
    $result[$key]['url'] = substr($result[$key]['url'], 0, $linkshrink);
    $result[$key]['sid'] = $session_id;

    $result[$key]['url_hash'] = hash("md5", $result[$key]['full_url']);
  }

  return $result;
}

/**
 * Implementation of hook_menu().
 */
function whami_source_adapter_menu() {
  $items = array();

  $items['whami/SourceAdapter'] = array(
    'title' => 'Whami SourceAdapter',
    'page callback' => 'whami_source_adapter_demo',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Function that implements a demo for the Source Adapter
 */
function whami_source_adapter_demo() {
  $session_id = check_plain($_COOKIE[session_name()]);

  // bbox -> "Ibiza"
  //  	'north' => 29,
  //  	'east' => -13,
  //    'south' => 27,
  //    'west' => -18
  // bbox -> Dublin
  //  	'north' => 53.419354,
  //  	'east' => -5.975189,
  //    'south' => 53.206855,
  //    'west' => -6.432495
  // bbox -> Australia
  //	'north' => -31.278551,
  //	'south' => -45.79817,
  //	'east' => 154.248047,
  //	'west' => 134.121094
  $a = whami_source_adapter_bounding_box(array(
    'north' => -31.278551,
    'south' => -45.79817,
    'east' => 154.248047,
    'west' => 134.121094
  ), 'de', array("03"), 'panoramio', 3, 10, 10, 10, 20, $session_id);
  $b = whami_source_adapter_geopoint_radius(40, -3, 10, 'es', array("03"), 'panoramio', 3, 10, 10, 10, 20, $session_id);

  $table_a = '<h2>whami_source_adapter_bounding_box</h2><br /> results for: whami_source_adapter_bounding_box(NULL, \'es\', array("01"), \'wikipedia\', 3, 10, 10, 10, 20)';
  $table_a .= theme_table(array_keys($a[0]), $a);

  $table_b = '<h2>whami_source_adapter_geopoint_radius</h2><br /> results for: whami_source_adapter_geopoint_radius(40,-3,10,\'es\',array("01"),\'wikipedia\', 3, 10, 10 , 10 , 20)';
  $table_b .= theme_table(array_keys($b[0]), $b);

  return $table_a . $table_b;
}

/**
 * This function converts a bounding box
 * of geographic data into a geographic
 * point and a radius that nears that bounding box
 *
 * @param double $north
 *   The longitude of the "upper/right" geopoint
 * @param double $east
 *   The latitude of the "upper/right" geopoint
 * @param double $south
 *   The longitude of the "lower/left" geopoint
 * @param double $west
 *   The latitude of the "lower/left" geopoint
 *
 * @return
 *   A one-dimensional array with the lon of the geopoint,
 *   the lat of the geopoint and the radius
 */
function whami_source_adapter_convert_bbox_geopoint_radius($north, $east, $south, $west) {
  $dist_two_lon = 40075.017 / 360;
  $dist_two_lat = 20003.9315 / 180;

  $dist_lon = 0;
  $lat = 0;
  if ( $east >= $west ) {
    $dist_lon = ($east - $west) * $dist_two_lon;
    $lon = 0.5 * ($east + $west);
  }
  else {
    $dist_lon = (360 + $east - $west) * $dist_two_lon;
    $lon = 180 + (0.5 * ($east + $west));
  }

  if ( $lon > 180 ) {
    $lon = $lon - 360;
  }

  $dist_lat = ($north - $south) * $dist_two_lat;
  $lat = 0.5 * ($north + $south);

  $radius = 0.5 * sqrt(($dist_lon * $dist_lon) + ($dist_lat * $dist_lat));

  return array('lon' => $lon, 'lat' => $lat, 'radius' => $radius);
}

/**
 * This function converts a "geographic circle" into
 * bounding box denoted by 2 geopoints
 *
 * @param double $lon
 *   The longitude of the geographic point
 * @param double $lat
 *   The latitude of the geographic point
 * @param $radius
 *   The radius of the geographic circle
 *
 * @return array
 *   A one-dimensional array denoting two geograpic points which
 *   combined form a geographic bounding box
 */
function whami_source_adapter_convert_geopoint_radius_bbox($lon, $lat, $radius) {
  $earth_length = 40075.017;
  $earth_breadth = 20003.9315;

  $length = ($radius * 360 / $earth_length);
  $east = $lon + $length;
  $west = $lon - $length;

  $east = $east <= 180 ? $east : $east - 360;
  $west = $west >= -180 ? $west : $west + 360;

  $breadth = ($radius * 180 / $earth_breadth);
  $north = $lat + $breadth;
  $south = $lat - $breadth;

  $north = $north > 90 ? 90 : $north;
  $south = $south < -90 ? -90 : $south;

  return array('north' => $north, 'east' => $east, 'south' => $south, 'west' => $west);
}
