<?php

/**
 *
 * Implementation of hook_menu()
 */
function whami_map_toolkit_menu() {
  $items = array();

  $items['admin/settings/whami_map_toolkit'] = array(
      'title' => t('whami Map Toolkit settings'),
      'description' => t('configure the settings for your maps'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('_whami_map_toolkit_admin_settings_form'),
      'access arguments' => array('access administration pages'),
      'file' => 'whami_map_toolkit.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_mapstraction_cck_node_map_rendered
 *
 * @param $node
 * @param $field_name
 * @param $mapid
 */
function whami_map_toolkit_mapstraction_cck_node_map_rendered($node, $field_name, $mapid) {

  module_load_include('inc', 'whami_map_toolkit', 'whami_map_toolkit.admin');
  $enabled_types = _whami_map_toolkit_get_enabled_content_types();

  if ( array_search($node->type, $enabled_types) ) {

    //Get place of node map
    if (function_exists('whami_source_adapter_get_place_for_nid')) {
      $client_place = whami_source_adapter_get_place_for_nid($node);
    }
    else {
      module_load_include('inc', 'whami_map_toolkit');
      $client_place = whami_create_place_from_node($node, $field_name, $mapid);
    }
    $node_places = array($client_place['url_hash'] => $client_place);

    $radius = _whami_map_toolkit_conf_variable_value('SEARCH_RADIUS', 5);

    if (function_exists('whami_source_adapter_geopoint_radius')) {
      $source_places = whami_source_adapter_geopoint_radius(
        $client_place['latitude'],
        $client_place['longitude'],
        $radius,
        _whami_map_toolkit_get_enabled_sources(),
        '', //$langcode
        _whami_map_toolkit_conf_variable_value('MAX_RESULTS', 5),
        _whami_map_toolkit_conf_variable_value('MAX_REQUEST', 5)
      );

      $node_places = array_merge($node_places, $source_places);
    }

    //Add place to page in Client/JS-context
    $whami_js_settings['map_places'] = array( $mapid => $node_places);
    $whami_js_settings['node_map_place'] = array( $mapid => $client_place['url_hash']);
    $whami_js_settings['map_radius'] = array( $mapid => $radius);
//    if (function_exists('whami_source_adapter_convert_geopoint_radius_bbox'))
//      $whami_js_settings['node_map_bbox'] = array($mapid => whami_source_adapter_convert_geopoint_radius_bbox($client_place['latitude'], $client_place['longitude'], $radius));

    drupal_add_js(array('whami' => $whami_js_settings), "setting");

    whami_set_map_settings($mapid, 'node_view');

    return 'whami_map_toolkit_init';
  }
}
