<?php
module_load_include('inc', 'whami_source_adapter_facebook', 'whami_source_adapter_facebook_toolkit');

/**
 * Implementation of hook_menu()
 */
function whami_source_adapter_facebook_menu() {
  $items = array();

  $items['admin/settings/whami_source_adapter_facebook'] = array(
      'title' => t('whami Source Adapter Facebook settings'),
      'description' => t('configure the settings for the whami Source Adapter Facebook'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('_whami_source_adapter_facebook_admin'),
      'access arguments' => array('access whami facebook settings'),
      'file' => 'whami_source_adapter_facebook.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perm()
 */
function whami_source_adapter_facebook_perm() {
  return array('access whami facebook settings');
}

/**
 * Implementation of hook_whami_sources_info()
 */
function whami_source_adapter_facebook_whami_source_info($source) {
  global $base_url;
//  module_load_include('inc', 'whami_source_adapter');
  $module_path = drupal_get_path('module', 'whami_source_adapter_facebook');

  $source['source_image'] = array(
          'filepath' => url($base_url . '/' . $module_path . '/images/facebook-image.png'),
      );
  $source['source_logo'] = array(
          'filepath' => url($base_url . '/' . $module_path . '/images/facebook-logo.png'),
      );
  $source['map_display_icon'] = url($base_url . '/' . $module_path . '/images/facebook-marker.gif');

  $source['type'] = 'Page';

  return $source;
}

function whami_source_adapter_facebook_add_styles() {
  drupal_add_css(drupal_get_path('module', 'whami_source_adapter_facebook') . '/theme/' . 'whami_source_adapter_facebook.css', 'module');
}
